const primary = [{"id":1,"sender_name":"Gertie","subject":"Implemented solution-oriented protocol","time":"8:02 PM","is_read":true},
{"id":2,"sender_name":"Bank","subject":"Advanced background methodology","time":"2:09 AM","is_read":true},
{"id":3,"sender_name":"Charil","subject":"Open-source attitude-oriented matrices","time":"8:07 AM","is_read":false},
{"id":4,"sender_name":"Cindi","subject":"Focused eco-centric monitoring","time":"9:03 PM","is_read":false},
{"id":5,"sender_name":"Aguistin","subject":"Multi-tiered high-level intranet","time":"3:23 PM","is_read":true},
{"id":6,"sender_name":"Sherwynd","subject":"Open-architected global archive","time":"6:04 AM","is_read":true},
{"id":7,"sender_name":"Elyn","subject":"Secured didactic process improvement","time":"11:11 AM","is_read":true},
{"id":8,"sender_name":"Carmelia","subject":"Fully-configurable attitude-oriented hub","time":"3:31 AM","is_read":false},
{"id":9,"sender_name":"Larisa","subject":"Cloned directional hardware","time":"6:18 PM","is_read":false},
{"id":10,"sender_name":"Robby","subject":"Exclusive client-driven firmware","time":"10:57 PM","is_read":true},
{"id":11,"sender_name":"Oliver","subject":"Cross-group value-added software","time":"9:47 PM","is_read":true},
{"id":12,"sender_name":"Wandis","subject":"Progressive eco-centric installation","time":"5:13 AM","is_read":true},
{"id":13,"sender_name":"Jacinta","subject":"Distributed asynchronous architecture","time":"8:01 PM","is_read":false},
{"id":14,"sender_name":"Theresina","subject":"Distributed 6th generation conglomeration","time":"6:21 PM","is_read":false},
{"id":15,"sender_name":"Rivkah","subject":"Universal even-keeled hub","time":"11:56 AM","is_read":true},
{"id":16,"sender_name":"Goldie","subject":"Seamless exuding customer loyalty","time":"6:35 AM","is_read":true},
{"id":17,"sender_name":"Lacie","subject":"Open-source regional encryption","time":"9:27 AM","is_read":true},
{"id":18,"sender_name":"Aggie","subject":"Seamless motivating utilisation","time":"7:01 AM","is_read":false},
{"id":19,"sender_name":"Hodge","subject":"Re-engineered systematic analyzer","time":"8:50 AM","is_read":true},
{"id":20,"sender_name":"Zia","subject":"Future-proofed multi-state application","time":"10:21 AM","is_read":false},
{"id":21,"sender_name":"Judy","subject":"Multi-channelled regional utilisation","time":"3:46 AM","is_read":false},
{"id":22,"sender_name":"Kym","subject":"Face to face solution-oriented function","time":"1:33 PM","is_read":true},
{"id":23,"sender_name":"Rufus","subject":"Cloned logistical firmware","time":"12:51 PM","is_read":true},
{"id":24,"sender_name":"Humfrey","subject":"Versatile demand-driven neural-net","time":"8:31 PM","is_read":true},
{"id":25,"sender_name":"Barnett","subject":"Configurable asymmetric customer loyalty","time":"4:28 PM","is_read":true},
{"id":26,"sender_name":"Ellyn","subject":"Implemented neutral groupware","time":"4:03 AM","is_read":true},
{"id":27,"sender_name":"Fawn","subject":"Reduced content-based extranet","time":"6:07 PM","is_read":false},
{"id":28,"sender_name":"Lothaire","subject":"Reduced mobile collaboration","time":"7:05 PM","is_read":true},
{"id":29,"sender_name":"Daren","subject":"Robust dynamic methodology","time":"2:36 PM","is_read":false},
{"id":30,"sender_name":"Wendall","subject":"Devolved uniform paradigm","time":"1:21 PM","is_read":true},
{"id":31,"sender_name":"Dominique","subject":"Polarised 5th generation customer loyalty","time":"3:38 PM","is_read":false},
{"id":32,"sender_name":"Gilligan","subject":"Face to face interactive moderator","time":"6:15 AM","is_read":true},
{"id":33,"sender_name":"Damara","subject":"Down-sized user-facing time-frame","time":"11:21 PM","is_read":false},
{"id":34,"sender_name":"Tonya","subject":"Multi-channelled mobile interface","time":"10:44 PM","is_read":false},
{"id":35,"sender_name":"Sydney","subject":"Operative coherent local area network","time":"3:05 AM","is_read":false},
{"id":36,"sender_name":"Derry","subject":"Sharable client-driven monitoring","time":"9:29 AM","is_read":false},
{"id":37,"sender_name":"Benetta","subject":"Extended national productivity","time":"9:28 PM","is_read":false},
{"id":38,"sender_name":"Donall","subject":"De-engineered eco-centric local area network","time":"1:27 PM","is_read":false},
{"id":39,"sender_name":"Neille","subject":"Multi-lateral hybrid superstructure","time":"3:16 PM","is_read":false},
{"id":40,"sender_name":"Dudley","subject":"Realigned upward-trending emulation","time":"7:48 AM","is_read":false},

{"id":41,"sender_name":"Lars","subject":"Open-architected client-server function","time":"3:58 AM","is_read":true},
{"id":42,"sender_name":"Orel","subject":"User-friendly non-volatile framework","time":"3:37 AM","is_read":false},
{"id":43,"sender_name":"Harlin","subject":"Synergistic optimal analyzer","time":"6:43 AM","is_read":false},
{"id":44,"sender_name":"Gothart","subject":"Robust hybrid functionalities","time":"5:04 PM","is_read":false},
{"id":45,"sender_name":"Spencer","subject":"Exclusive foreground info-mediaries","time":"11:06 AM","is_read":true},
{"id":46,"sender_name":"Ripley","subject":"Sharable empowering instruction set","time":"11:48 AM","is_read":false},
{"id":47,"sender_name":"Gilles","subject":"Horizontal tangible matrix","time":"4:12 PM","is_read":false},
{"id":48,"sender_name":"Abbe","subject":"Optimized actuating extranet","time":"12:46 PM","is_read":false},
{"id":49,"sender_name":"Spense","subject":"Diverse stable pricing structure","time":"1:04 AM","is_read":false},
{"id":50,"sender_name":"Cody","subject":"Right-sized system-worthy synergy","time":"3:15 AM","is_read":true},]

const social = [
    {"id":51,"sender_name":"Aguie","subject":"Quality-focused methodical task-force","time":"10:19 AM","is_read":true},
    {"id":52,"sender_name":"Danita","subject":"Centralized fresh-thinking forecast","time":"5:09 AM","is_read":false},
    {"id":53,"sender_name":"Kaycee","subject":"Down-sized hybrid throughput","time":"1:49 AM","is_read":false},
    {"id":54,"sender_name":"Mariele","subject":"Managed local implementation","time":"1:04 AM","is_read":false},
    {"id":55,"sender_name":"Billie","subject":"Team-oriented even-keeled matrix","time":"12:15 PM","is_read":true},
    {"id":56,"sender_name":"Otis","subject":"Customizable asynchronous knowledge base","time":"6:35 PM","is_read":false},
    {"id":57,"sender_name":"Raul","subject":"Quality-focused 3rd generation contingency","time":"10:54 PM","is_read":false},
    {"id":58,"sender_name":"Madella","subject":"Face to face user-facing paradigm","time":"6:53 PM","is_read":false},
    {"id":59,"sender_name":"Francklyn","subject":"Secured upward-trending Graphic Interface","time":"8:54 PM","is_read":false},
    {"id":60,"sender_name":"Bradney","subject":"Cross-group homogeneous benchmark","time":"8:14 AM","is_read":false},
    {"id":61,"sender_name":"Bryn","subject":"Synchronised web-enabled framework","time":"1:52 AM","is_read":true},
    {"id":62,"sender_name":"Francois","subject":"Cloned full-range archive","time":"5:24 AM","is_read":false},
    {"id":63,"sender_name":"Issiah","subject":"Visionary upward-trending pricing structure","time":"11:57 PM","is_read":false},
    {"id":64,"sender_name":"Barton","subject":"Business-focused cohesive intranet","time":"10:33 PM","is_read":false},
    {"id":65,"sender_name":"Jolyn","subject":"Switchable methodical challenge","time":"10:00 AM","is_read":true},
    {"id":66,"sender_name":"Stillmann","subject":"Centralized 5th generation protocol","time":"3:09 PM","is_read":true},
    {"id":67,"sender_name":"Pauli","subject":"Programmable zero administration moratorium","time":"6:15 AM","is_read":false},
    {"id":68,"sender_name":"Lucio","subject":"Cross-platform composite flexibility","time":"10:09 AM","is_read":false},
    {"id":69,"sender_name":"Winonah","subject":"Versatile real-time data-warehouse","time":"7:11 PM","is_read":true},
    {"id":70,"sender_name":"Carie","subject":"Phased neutral monitoring","time":"11:11 AM","is_read":false},
    {"id":71,"sender_name":"Jewell","subject":"Operative executive interface","time":"6:51 AM","is_read":false},
    {"id":72,"sender_name":"Devinne","subject":"Adaptive client-driven functionalities","time":"5:16 AM","is_read":false},
    {"id":73,"sender_name":"Vinson","subject":"Streamlined fault-tolerant data-warehouse","time":"5:09 AM","is_read":true},
    {"id":74,"sender_name":"Eleen","subject":"Synergistic executive archive","time":"6:57 PM","is_read":false},
    {"id":75,"sender_name":"Waite","subject":"Open-architected 6th generation artificial intelligence","time":"12:15 PM","is_read":false},
    {"id":76,"sender_name":"Raffarty","subject":"Polarised regional task-force","time":"4:31 PM","is_read":false},
    {"id":77,"sender_name":"Carol","subject":"Persevering exuding architecture","time":"4:36 PM","is_read":false},
    {"id":78,"sender_name":"Eleen","subject":"Vision-oriented modular core","time":"8:20 PM","is_read":false},
    {"id":79,"sender_name":"Gothart","subject":"Monitored optimal local area network","time":"5:19 PM","is_read":false},
    {"id":80,"sender_name":"Marice","subject":"Inverse encompassing intranet","time":"4:13 AM","is_read":true},
    {"id":81,"sender_name":"Timoteo","subject":"Advanced multi-state challenge","time":"1:10 PM","is_read":true},
    {"id":82,"sender_name":"Cecilia","subject":"Multi-channelled mission-critical Graphical User Interface","time":"8:54 PM","is_read":false},
    {"id":83,"sender_name":"Arliene","subject":"Assimilated object-oriented installation","time":"9:19 AM","is_read":true},
    {"id":84,"sender_name":"Emmey","subject":"Pre-emptive optimal ability","time":"4:54 PM","is_read":false},
    {"id":85,"sender_name":"Sheila-kathryn","subject":"Synchronised local hierarchy","time":"5:17 AM","is_read":false},
    {"id":86,"sender_name":"Zacharie","subject":"Integrated intangible alliance","time":"4:14 AM","is_read":true},
    {"id":87,"sender_name":"Bobinette","subject":"Reverse-engineered 3rd generation leverage","time":"6:41 PM","is_read":false},
    {"id":88,"sender_name":"Davey","subject":"Business-focused stable matrices","time":"9:42 PM","is_read":true},
    {"id":89,"sender_name":"Sibella","subject":"Reduced homogeneous frame","time":"7:39 AM","is_read":true},
    {"id":90,"sender_name":"Paulette","subject":"Optimized incremental migration","time":"2:59 AM","is_read":false},
    {"id":91,"sender_name":"Olwen","subject":"Expanded full-range extranet","time":"6:45 PM","is_read":true},
    {"id":92,"sender_name":"Dulcia","subject":"Reduced fresh-thinking capability","time":"8:36 AM","is_read":true},
    {"id":93,"sender_name":"Manon","subject":"Implemented maximized extranet","time":"2:58 PM","is_read":true},
    {"id":94,"sender_name":"Erskine","subject":"Enhanced discrete alliance","time":"3:36 AM","is_read":true},
    {"id":95,"sender_name":"Elvyn","subject":"Robust dynamic protocol","time":"5:14 PM","is_read":false},
    {"id":96,"sender_name":"Sande","subject":"Persevering high-level concept","time":"10:51 AM","is_read":true},
    {"id":97,"sender_name":"Jimmie","subject":"Quality-focused even-keeled open architecture","time":"10:16 PM","is_read":false},
    {"id":98,"sender_name":"Von","subject":"Switchable multi-state algorithm","time":"9:58 AM","is_read":false},
    {"id":99,"sender_name":"Rooney","subject":"De-engineered intermediate concept","time":"11:16 AM","is_read":false},
    {"id":100,"sender_name":"Sibel","subject":"Future-proofed incremental moratorium","time":"4:29 AM","is_read":false},  
]

const promotion = [
    {"id":101,"sender_name":"Marcos","subject":"Secured value-added methodology","time":"3:50 AM","is_read":true},
    {"id":102,"sender_name":"Dela","subject":"Sharable explicit project","time":"2:14 AM","is_read":false},
    {"id":103,"sender_name":"Marsiella","subject":"Synergized zero tolerance Graphical User Interface","time":"12:42 AM","is_read":true},
    {"id":104,"sender_name":"Noell","subject":"Reduced eco-centric projection","time":"5:00 AM","is_read":true},
    {"id":105,"sender_name":"Harold","subject":"Optimized multi-tasking adapter","time":"10:12 AM","is_read":false},
    {"id":106,"sender_name":"Arlette","subject":"Innovative real-time capacity","time":"4:18 PM","is_read":true},
    {"id":107,"sender_name":"Sherline","subject":"Diverse full-range flexibility","time":"1:57 AM","is_read":true},
    {"id":108,"sender_name":"Jordana","subject":"Profound zero administration toolset","time":"9:02 PM","is_read":true},
    {"id":109,"sender_name":"Peggie","subject":"Right-sized regional encryption","time":"1:52 AM","is_read":false},
    {"id":110,"sender_name":"Neilla","subject":"Triple-buffered human-resource encryption","time":"6:14 PM","is_read":true},
    {"id":111,"sender_name":"Matthaeus","subject":"De-engineered empowering groupware","time":"7:20 AM","is_read":true},
    {"id":112,"sender_name":"Coleman","subject":"Intuitive object-oriented benchmark","time":"7:41 PM","is_read":false},
    {"id":113,"sender_name":"Leo","subject":"Focused full-range encryption","time":"1:16 AM","is_read":false},
    {"id":114,"sender_name":"Tonie","subject":"Cross-group bi-directional productivity","time":"10:01 PM","is_read":true},
    {"id":115,"sender_name":"Myron","subject":"Public-key multi-tasking pricing structure","time":"1:06 PM","is_read":false},
    {"id":116,"sender_name":"Marcile","subject":"Open-source even-keeled definition","time":"2:10 AM","is_read":false},
    {"id":117,"sender_name":"Georgetta","subject":"Proactive intermediate parallelism","time":"3:35 AM","is_read":true},
    {"id":118,"sender_name":"Bernita","subject":"Phased zero defect policy","time":"5:02 AM","is_read":false},
    {"id":119,"sender_name":"Waverley","subject":"Managed high-level access","time":"11:45 PM","is_read":true},
    {"id":120,"sender_name":"Clayborn","subject":"Seamless attitude-oriented collaboration","time":"11:44 AM","is_read":false},
    {"id":121,"sender_name":"Curran","subject":"Triple-buffered modular matrix","time":"7:45 PM","is_read":false},
    {"id":122,"sender_name":"Deeyn","subject":"Cross-platform needs-based synergy","time":"6:25 PM","is_read":false},
    {"id":123,"sender_name":"Maxy","subject":"Open-source explicit customer loyalty","time":"2:30 AM","is_read":true},
    {"id":124,"sender_name":"Emmalynne","subject":"Focused tangible superstructure","time":"2:09 AM","is_read":false},
    {"id":125,"sender_name":"Maudie","subject":"Versatile clear-thinking synergy","time":"9:40 AM","is_read":false},
    {"id":126,"sender_name":"Jan","subject":"Centralized even-keeled customer loyalty","time":"3:58 AM","is_read":true},
    {"id":127,"sender_name":"Broddy","subject":"Multi-lateral uniform projection","time":"10:19 AM","is_read":false},
    {"id":128,"sender_name":"Franciska","subject":"Diverse bandwidth-monitored internet solution","time":"1:01 AM","is_read":false},
    {"id":129,"sender_name":"Aaron","subject":"Upgradable multimedia database","time":"9:00 AM","is_read":false},
    {"id":130,"sender_name":"Bibbie","subject":"Networked 6th generation info-mediaries","time":"3:54 PM","is_read":true},
    {"id":131,"sender_name":"Ruddie","subject":"User-centric grid-enabled challenge","time":"11:43 AM","is_read":false},
    {"id":132,"sender_name":"Tabby","subject":"Reduced content-based structure","time":"12:27 PM","is_read":false},
    {"id":133,"sender_name":"Millie","subject":"Triple-buffered transitional secured line","time":"7:09 AM","is_read":true},
    {"id":134,"sender_name":"Minette","subject":"Adaptive upward-trending function","time":"11:28 AM","is_read":false},
    {"id":135,"sender_name":"Rebekkah","subject":"Open-architected 24/7 functionalities","time":"3:07 AM","is_read":false},
    {"id":136,"sender_name":"Gwennie","subject":"Self-enabling asynchronous task-force","time":"2:10 PM","is_read":true},
    {"id":137,"sender_name":"Roseann","subject":"Stand-alone analyzing attitude","time":"6:01 PM","is_read":false},
    {"id":138,"sender_name":"Hilde","subject":"Exclusive eco-centric analyzer","time":"1:07 AM","is_read":true},
    {"id":139,"sender_name":"Cosetta","subject":"Team-oriented maximized solution","time":"11:14 AM","is_read":false},
    {"id":140,"sender_name":"Stefan","subject":"Centralized hybrid synergy","time":"10:02 AM","is_read":true},
    {"id":141,"sender_name":"Colet","subject":"Grass-roots empowering focus group","time":"12:18 AM","is_read":true},
    {"id":142,"sender_name":"Carey","subject":"Cross-group web-enabled function","time":"6:06 AM","is_read":false},
    {"id":143,"sender_name":"Red","subject":"Fully-configurable regional service-desk","time":"9:53 AM","is_read":false},
    {"id":144,"sender_name":"Fara","subject":"Open-architected user-facing open architecture","time":"3:04 AM","is_read":true},
    {"id":145,"sender_name":"Paloma","subject":"Ameliorated scalable structure","time":"1:51 AM","is_read":true},
    {"id":146,"sender_name":"Tiler","subject":"Reactive homogeneous challenge","time":"6:14 PM","is_read":false},
    {"id":147,"sender_name":"Cheri","subject":"Devolved national orchestration","time":"12:14 AM","is_read":true},
    {"id":148,"sender_name":"Kirbie","subject":"Universal needs-based support","time":"4:41 PM","is_read":false},
    {"id":149,"sender_name":"Clea","subject":"Profound intangible function","time":"9:27 AM","is_read":false},
    {"id":150,"sender_name":"Mavra","subject":"Ergonomic radical parallelism","time":"1:08 AM","is_read":true},]

    export default {
        primary,
        social,
        promotion
    }